TestDev/TrueWheels.Web/Controllers/RentSpaceController.cs
using Excel;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrueWheels.BEL;
using TrueWheels.DAL;
using TrueWheels.Web.Models;

namespace TrueWheels.Web.Controllers
{
    public class RentSpaceController : Controller
    {
        //
        // GET: /RentSpace/
        public ActionResult CreateSpace()
        {
            return View();
        }

        public ActionResult UploadSpace(HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {

                if (upload != null && upload.ContentLength > 0)
                {
                    // ExcelDataReader works with the binary Excel file, so it needs a FileStream
                    // to get started. This is how we avoid dependencies on ACE or Interop:
                    Stream stream = upload.InputStream;

                    // We return the interface, so that
                    IExcelDataReader reader = null;


                    if (upload.FileName.EndsWith(".xls"))
                    {
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    }
                    else if (upload.FileName.EndsWith(".xlsx"))
                    {
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    else
                    {
                        ModelState.AddModelError("File", "This file format is not supported");
                        return View();
                    }

                    reader.IsFirstRowAsColumnNames = true;
                    //reader.
                    DataSet result = reader.AsDataSet();
                    reader.Close();
                    // start
                    DataColumn column = new DataColumn();
                    column.ColumnName = "Registered";
                    result.Tables[0].Columns.Add(column);
                    column = new DataColumn();
                    column.ColumnName = "ErrorMessage";
                    result.Tables[0].Columns.Add(column);
                    ParkingAreaDAL Parkingdal = new ParkingAreaDAL();
                    RegisterParkingAreaBEL ParkingBEL = new RegisterParkingAreaBEL();
                    RegsiterParkingAreaResult ParkingResult = new RegsiterParkingAreaResult();
                    for (int i=0;i<=result.Tables[0].Rows.Count-1;i++)
                    {
                        ParkingResult.ErrorMessage = "";
                        if (result.Tables[0].Rows[i]["owner_id"] != null && Convert.ToString(result.Tables[0].Rows[i]["owner_id"]) != "")
                            ParkingBEL.owner_id = Convert.ToInt32(result.Tables[0].Rows[i]["owner_id"]);
                        else
                            ParkingResult.ErrorMessage = "owner id can not be blank. ";

                        if (result.Tables[0].Rows[i]["Space_type"] != null && Convert.ToString(result.Tables[0].Rows[i]["Space_type"]) != "")
                           ParkingBEL.Space_type = Convert.ToString(result.Tables[0].Rows[i]["Space_type"]);
                        else
                            ParkingResult.ErrorMessage += " Space_type can not be blank. ";

                        if (result.Tables[0].Rows[i]["Property_type"] != null && Convert.ToString(result.Tables[0].Rows[i]["Property_type"]) != "")
                           ParkingBEL.Property_type = Convert.ToString(result.Tables[0].Rows[i]["Property_type"]);
                        else
                            ParkingResult.ErrorMessage += " Property_type can not be blank. ";

                        if (result.Tables[0].Rows[i]["No_of_space"] != null && Convert.ToString(result.Tables[0].Rows[i]["No_of_space"]) != "" )
                        ParkingBEL.No_of_space = Convert.ToString(result.Tables[0].Rows[i]["No_of_space"]);
                        else
                            ParkingResult.ErrorMessage += " No_of_space can not be blank. ";

                        if (result.Tables[0].Rows[i]["VechileType"] != null && Convert.ToString(result.Tables[0].Rows[i]["VechileType"]) != "")
                        ParkingBEL.VechileType = Convert.ToString(result.Tables[0].Rows[i]["VechileType"]);
                        else
                            ParkingResult.ErrorMessage += " VechileType can not be blank. ";

                        if (result.Tables[0].Rows[i]["PropertyVerifiedStatus"] != null && Convert.ToString(result.Tables[0].Rows[i]["PropertyVerifiedStatus"]) != "")
                        ParkingBEL.PropertyVerifiedStatus = Convert.ToString(result.Tables[0].Rows[i]["PropertyVerifiedStatus"]);
                        else
                            ParkingResult.ErrorMessage += " PropertyVerifiedStatus can not be blank. ";

                        ParkingBEL.FacilityGroupId = Convert.ToString(result.Tables[0].Rows[i]["FacilityGroupId"]);

                        if (result.Tables[0].Rows[i]["PropertyAddress"] != null && Convert.ToString(result.Tables[0].Rows[i]["PropertyAddress"]) != "")
                        ParkingBEL.PropertyAddress = Convert.ToString(result.Tables[0].Rows[i]["PropertyAddress"]);
                        else
                            ParkingResult.ErrorMessage += " No_of_space can not be blank. ";

                        if (result.Tables[0].Rows[i]["PropertyPinCode"] != null && Convert.ToString(result.Tables[0].Rows[i]["PropertyPinCode"]) != "")
                        ParkingBEL.PropertyPinCode = Convert.ToInt32(result.Tables[0].Rows[i]["PropertyPinCode"]);
                        else
                            ParkingResult.ErrorMessage += " PropertyPinCode can not be blank. ";

                        ParkingBEL.PropertyZone = Convert.ToString(result.Tables[0].Rows[i]["PropertyZone"]);

                        ParkingBEL.PropertyLandMark = Convert.ToString(result.Tables[0].Rows[i]["PropertyLandMark"]);

                        ParkingBEL.OwnerComments = Convert.ToString(result.Tables[0].Rows[i]["OwnerComments"]);

                        if (result.Tables[0].Rows[i]["lattitude"] != null && Convert.ToString(result.Tables[0].Rows[i]["lattitude"]) != "")
                        ParkingBEL.lattitude = Convert.ToString(result.Tables[0].Rows[i]["lattitude"]);
                        else
                            ParkingResult.ErrorMessage += " lattitude can not be blank. ";

                        if (result.Tables[0].Rows[i]["longitude"] != null && Convert.ToString(result.Tables[0].Rows[i]["longitude"]) != "")
                        ParkingBEL.longitude = Convert.ToString(result.Tables[0].Rows[i]["longitude"]);
                        else
                            ParkingResult.ErrorMessage += " longitude can not be blank. ";
                        if (ParkingResult.ErrorMessage == "")
                        {
                            ParkingResult = Parkingdal.RegisterParkingArea(ParkingBEL);

                            if (ParkingResult.ErrorMessage == "" && ParkingResult.Parking_Id != 0)
                            {
                                result.Tables[0].Rows[i]["Registered"] = "True";

                            }
                            else
                            {
                                result.Tables[0].Rows[i]["Registered"] = "False";
                                result.Tables[0].Rows[i]["ErrorMessage"] = ParkingResult.ErrorMessage;
                            }
                        }
                        else
                        {
                            result.Tables[0].Rows[i]["Registered"] = "False";
                            result.Tables[0].Rows[i]["ErrorMessage"] = ParkingResult.ErrorMessage;
                        }
                    }
                    // end
                    return View(result.Tables[0]);
                }
                else
                {
                    ModelState.AddModelError("File", "Please Upload Your file");
                }
            }
            return View();
        }
    }
}

TestDev/TrueWheels.Web/Controllers/UserDashBaordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrueWheels.BEL;
using TrueWheels.DAL;
using TrueWheels.Web.Models;
using System.IO;

namespace TrueWheels.Web.Controllers
{
    public class UserDashBaordController : Controller
    {
        //
        // GET: /UserDashBaord/
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["userDetail"] != null)
            {
                UserMaintenanceViewModel objUserMaintenance = new UserMaintenanceViewModel();
                //List<DashBaordViewModal> DVM = new List<DashBaordViewModal>;
                UserDetailsDAL objUserDAL = new UserDetailsDAL();
                List<DashBoardBEL> UserMenus = objUserDAL.GetMenuMapping((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString());
                PersonalinfoBEL objPersonalInfo = objUserDAL.GetProfileInfo((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString());
                objPersonalInfo.profilePic_Path = objPersonalInfo.User_Id + ".png";
                objPersonalInfo.Full_Name = objPersonalInfo.First_Name + " " + objPersonalInfo.Last_Name;
                ViewBag.DashBoardMenu = UserMenus;
                objUserMaintenance.Personalinfo = objPersonalInfo;

                if (string.IsNullOrEmpty(UserMenus[0].ErrorMessage))
                {
                    //  DVM = UserMenus;
                    return View(objUserMaintenance);
                }
                else
                {

                    ModelState.AddModelError("", UserMenus[0].ErrorMessage.ToString());
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(PersonalinfoBEL profileInfo, HttpPostedFileBase profilePic)
         {
            if (ModelState.IsValid)
            {
                if (profilePic != null)
                {
                    var filename = profileInfo.User_Id + ".png";
                    var filePathOriginal = Server.MapPath("/Content/images/profilePicture");
                    string savedFileName = Path.Combine(filePathOriginal, filename);
                    string path = System.Configuration.ConfigurationManager.AppSettings["appPath"] + savedFileName;
                    System.IO.File.Delete(savedFileName);
                    profilePic.SaveAs(savedFileName);
                }


                //List<DashBaordViewModal> DVM = new List<DashBaordViewModal>;
                UserDetailsDAL objUserDAL = new UserDetailsDAL();
                List<DashBoardBEL> UserMenus = objUserDAL.GetMenuMapping((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString());
                if (profileInfo.NewPassword == null)
                {
                    profileInfo.NewPassword = profileInfo.Password;
                }

                UserMaintenanceViewModel objUserMaintenance = new UserMaintenanceViewModel();

                objUserMaintenance.Personalinfo = objUserDAL.UpdateProfileInfo(profileInfo);
                objUserMaintenance.Personalinfo.profilePic_Path = objUserMaintenance.Personalinfo.User_Id + ".png";
                objUserMaintenance.Personalinfo.Full_Name = objUserMaintenance.Personalinfo.First_Name + " " + objUserMaintenance.Personalinfo.Last_Name;
                ViewBag.DashBoardMenu = UserMenus;

                if (string.IsNullOrEmpty(UserMenus[0].ErrorMessage))
                {
                    //  DVM = UserMenus;
                    return View(objUserMaintenance);
                }
                else
                {

                    ModelState.AddModelError("", UserMenus[0].ErrorMessage.ToString());
                    return View(objUserMaintenance);
                }
            }
            else
            {
                UserDetailsDAL objUserDAL = new UserDetailsDAL();
                List<DashBoardBEL> UserMenus = objUserDAL.GetMenuMapping((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString());
                ViewBag.DashBoardMenu = UserMenus;
                UserMaintenanceViewModel objUserMaintenance = new UserMaintenanceViewModel();
                objUserMaintenance.Personalinfo = profileInfo;
                return View(objUserMaintenance);
            }
        }

        //public ActionResult Index(string userid)
        //{


        //    return View();
        //}

        //
        // GET: /UserDashBaord/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /UserDashBaord/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /UserDashBaord/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /UserDashBaord/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /UserDashBaord/Edit/5
        [HttpPost]
        public ActionResult EditPersonalInfo(UserMaintenanceViewModel objUserMaintenance)
        {


            return RedirectToAction("Index");
        }

        //
        // GET: /UserDashBaord/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /UserDashBaord/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult FollowUs()
        {
            return PartialView("_FollowUs");
        }

        [HttpGet]
        public ActionResult InviteFriends()
        {
            return PartialView("_InviteFriends");
        }

        [HttpGet]
        public ActionResult Inbox()
        {
            UserDetailsDAL objUserDAL = new UserDetailsDAL();
            List<UserInboxBEL> ListUserNotifications = objUserDAL.GetUserInbox((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString());

            return PartialView("_Inbox", ListUserNotifications);
        }

        public ActionResult DeleteNotification(string id)
        {
            if (Session["userDetail"] != null)
            {
                UserDetailsDAL objUserDAL = new UserDetailsDAL();
                UserInboxBEL UserNotification = objUserDAL.DeleteUserNotification((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString(), id);
                if (UserNotification.Success)
                {
                    TempData["SaveSuccess"] = "Deleted Successfully";
                }
                else
                {
                    TempData["SaveSuccess"] = "An error occured";
                }
                List<UserInboxBEL> ListUserNotifications = objUserDAL.GetUserInbox((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString());

                return PartialView("_Inbox", ListUserNotifications);
            }
            else
            {
                return PartialView("_Inbox");
            }

        }


        [HttpGet]
        public ActionResult ViewProfile()
        {
            if (Session["userDetail"] != null)
            {
                UserMaintenanceViewModel objUserMaintenance = new UserMaintenanceViewModel();
                //List<DashBaordViewModal> DVM = new List<DashBaordViewModal>;
                UserDetailsDAL objUserDAL = new UserDetailsDAL();
                List<DashBoardBEL> UserMenus = objUserDAL.GetMenuMapping((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString());
                PersonalinfoBEL objPersonalInfo = objUserDAL.GetProfileInfo((((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID).ToString());
                objPersonalInfo.profilePic_Path = objPersonalInfo.User_Id + ".png";
                objPersonalInfo.Full_Name = objPersonalInfo.First_Name + " " + objPersonalInfo.Last_Name;
                ViewBag.DashBoardMenu = UserMenus;
                objUserMaintenance.Personalinfo = objPersonalInfo;

                if (string.IsNullOrEmpty(UserMenus[0].ErrorMessage))
                {
                    return PartialView("_Personalinfo", objPersonalInfo);
                }
                else
                {

                    ModelState.AddModelError("", UserMenus[0].ErrorMessage.ToString());
                }
            }

            return PartialView("_Personalinfo");
        }
    }
}

TestDev/TrueWheels.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <link href="~/Content/css/footer-distributed-with-address-and-phones.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content")
    @Scripts.Render("~/Content/js")


</head>

<body>

    <div class="header-connect">

        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-8 col-xs-8">
                    @*<div class="header-half header-call">
                            <p>
                                @if (Session["userDetail"] != null)
                                {
                                    if (((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_ID == "0")
                                    {
                                        <span><i class="icon-cloud"></i>Mobile_number</span>
                                        <span><i class="icon-mail"></i>EmailId</span>
                                    }
                                    else
                                    {
                                        <span><i class="icon-cloud"></i>@(((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).Phone_No1)</span>
                                        <span><i class="icon-mail"></i>@(((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).Email_Id)</span>
                                    }
                                }
                                else
                                {
                                    <span><i class="icon-cloud"></i>Mobile_number</span>
                                    <span><i class="icon-mail"></i>EmailId</span>
                                }
                            </p>
                        </div>*@
                </div>
                <div class="col-md-2 col-md-offset-5  col-sm-3 col-sm-offset-1  col-xs-3  col-xs-offset-1">
                    @*<div class="header-half header-social">
                            <ul class="list-inline">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-vine"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>*@

                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-default" style="border:0px">
        <div class="container btn-info" style="border:0px; border-bottom-left-radius:10px;border-bottom-right-radius:10px">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="row">
                <div class="col-md-3">
                    <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="padding-top:1px">
                        @*<img src="~/Content/img/DhiyaaishanbummiJPEG.jpg" class="img-responsive img-rounded">*@
                        <img src="~/Content/img/Logo.png" alt="" class="img-responsive img-rounded">
                        @*<img src="~/Content/img/DhiyaaishanbummiPNG.png" alt="" class="img-responsive img-rounded" />*@
                    </a>
                </div>
                <div class="col-md-9">
                    <div class="navbar-header" style="background-color:green; padding-top:2px">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>
                </div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse ">
                @if (Session["userDetail"] != null)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>Hello,@(((TrueWheels.Web.Models.UserLoginDetailsViewModel)(Session["userDetail"])).User_Name)</li>
                        <li>@Html.ActionLink("Logout", "LogOff", "TrueWheelsUser")</li>

                    </ul>
                }
                else
                {
                    <div class="button navbar-right">
                        <button class="navbar-btn nav-button wow bounceInRight login" data-wow-delay="0.8s" onclick="location.href= '@Url.Action("Login", "TrueWheelsUser")'">Login</button>
                        <button class="navbar-btn nav-button wow fadeInRight" data-wow-delay="0.6s" onclick="location.href= '@Url.Action("SignUp", "TrueWheelsUser")'">Sign up</button>
                    </div>
                }
                @*@if (Session["userDetail"] != null)
                    {
                        if (((TrueWheels.DAL.UserDetailsBEL)(Session["userDetail"])).User_ID == "0")
                        {
                            <div class="button navbar-right">
                                <button class="navbar-btn nav-button wow bounceInRight login" data-wow-delay="0.8s" onclick="location.href= '@Url.Action("Login", "TrueWheelsUser")'">Login</button>
                                <button class="navbar-btn nav-button wow fadeInRight" data-wow-delay="0.6s" onclick="location.href= '@Url.Action("SignUp", "TrueWheelsUser")'">Sign up</button>
                            </div>
                        }
                        else
                        { <div class="button navbar-right" style="font-family:Arial;font-size:18px;font-style:italic;padding-top:10px">
                            <p><b> Hello @(((TrueWheels.DAL.UserDetailsBEL)(Session["userDetail"])).User_Name) </b></p>
                              <button class="navbar-btn nav-button wow fadeInRight" data-wow-delay="0.6s" onclick="location.href= '@Url.Action("SignUp", "TrueWheelsUser")'">Sign up</button>
                        </div>
                        }
                    }
                    else
                    {
                        <div class="button navbar-right">
                            <button class="navbar-btn nav-button wow bounceInRight login" data-wow-delay="0.8s" onclick="location.href= '@Url.Action("Login", "TrueWheelsUser")'">Login</button>
                            <button class="navbar-btn nav-button wow fadeInRight" data-wow-delay="0.6s" onclick="location.href= '@Url.Action("SignUp", "TrueWheelsUser")'">Sign up</button>
                        </div>
                    }*@




                <ul class="main-nav nav navbar-nav navbar-right">
                    <li class="wow fadeInDown" data-wow-delay="0s">@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li class="wow fadeInDown disabled" data-wow-delay="0.1s"><a   href="@Url.Action("CreateSpace", "RentSpace")" >Rent out ur space</a></li>*@
                    <li class="wow fadeInDown" data-wow-delay="0.2s">
                        @if (Session["userDetail"] != null)
                        {
                            <a href="@Url.Action("Index", "UserDashBaord")">Dashboard</a>

                        }
                        else
                        {
                            <a href="@Url.Action("Login", "TrueWheelsUser")">Dashboard</a>
                        }
                    </li>

                    <li class="wow fadeInDown" data-wow-delay="0.4s"><a id="idHowitWorks" style="cursor:pointer">How it works</a></li>
                    <li class="wow fadeInDown" data-wow-delay="0.4s"><a href="@Url.Action("Index", "Home")">Popular Parking</a></li>
                    <li class="wow fadeInDown" data-wow-delay="0.3s"><a id="idAboutUS" style="cursor:pointer">About us</a></li>
                    <li class="wow fadeInDown" data-wow-delay="0.5s"><a id="idContactUs" style="cursor:pointer">Contact</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <!-- <div class="navbar navbar-inverse navbar-fixed-top">
         <div class="container">
             <div class="navbar-header">
                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                 </button>
                 @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
             </div>
             <div class="navbar-collapse collapse">
                 <ul class="nav navbar-nav">
                     <li>@Html.ActionLink("Home", "Index", "Home")</li>
                     <li>@Html.ActionLink("About", "About", "Home")</li>
                     <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                 </ul>
             </div>
         </div>
     </div>-->

    <div class="row"><br /><br /></div>
    @RenderBody()
    @RenderSection("scripts", required: false)
    <div class="">
        @*<footer class="fadeInDown">*@
        @*<p>&copy; @DateTime.Now.Year - Ganeis</p>
                </p>
            </footer>*@
        <footer class="footer-distributed">

            <div class="footer-left">

                <h3>Company<span>logo</span></h3>

                <p class="footer-links">
                    <a href="#">Home</a>
                    ·
                    <a href="#">Blog</a>
                    ·
                    <a href="#">Pricing</a>
                    ·
                    <a href="#">About</a>
                    ·
                    <a href="#">Faq</a>
                    ·
                    <a href="#">Contact</a>
                </p>

                <p class="footer-company-name">@DateTime.Now.Year - Ganeis</p>
            </div>

            <div class="footer-center">

                <div>
                    <i class="fa fa-map-marker"></i>
                    <p><span>21 Revolution Street</span> Paris, France</p>
                </div>

                <div>
                    <i class="fa fa-phone"></i>
                    <p>+1 555 123456</p>
                </div>

                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="mailto:support@company.com">support@company.com</a></p>
                </div>

            </div>

            <div class="footer-right">

                <p class="footer-company-about">
                    <span>About the company</span>
                    Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
                </p>

                <div class="footer-icons">

                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>
                    <a href="#"><i class="fa fa-github"></i></a>

                </div>

            </div>

        </footer>
    </div>



</body>
</html>