TestDev/TrueWheels.Web/Models/ParkingAreaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TrueWheels.Web.Models
{

    public class ParkingAreaViewModel
    {

        public decimal Main_Latitude { get; set; }


        public decimal Main_Longitude { get; set; }


        public int Distance { get; set; }


        public string FromDateTime { get; set; }

        public string ToDateTime { get; set; }

        public string ParkingClass { get; set; }

        public string OrderBy { get; set; }
        public ParkingAreaViewModel()
        {

        }


    }

    public class ParkingAreaResultViewModel
    {

        public string Parking_id { get; set; }

        public string parking_address { get; set; }

        public string street { get; set; }

        public string city { get; set; }
        public string state { get; set; }
        public string lattitude { get; set; }
        public string longitude { get; set; }
        public string GeoLoc { get; set; }
        public string DateTimeTo { get; set; }
        public string DateTimeFrom { get; set; }
        public string No_Of_Space_Avaiable { get; set; }
        public string Detail_ID { get; set; }
        public int BasicCharge { get; set; }
        public string ParkingClass { get; set; }


        


    }
}

TestDev/TrueWheels.Web/Controllers/ParkingAreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrueWheels.Web.Models;
using TrueWheels.BEL;
using TrueWheels.DAL;
//using TrueWheels.DEL;
using System.Web.Script.Serialization;
using Newtonsoft.Json;

namespace TrueWheels.Web.Controllers
{
    public class ParkingAreaController : Controller
    {
        //
        // GET: /ParkingArea/
        
        public ActionResult Index(ParkingAreaViewModel vm)
        {
            ParkingAreaViewModel parkingViewMoel = TempData["ParkingAreaViewModel"] as ParkingAreaViewModel;
            ParkingAreaBEL parking = new ParkingAreaBEL();
            parking.Distance = vm.Distance;
            parking.FromDateTime = vm.FromDateTime;
            parking.Main_Latitude = vm.Main_Latitude;
            parking.Main_Longitude = vm.Main_Longitude;
            parking.ParkingClass = vm.ParkingClass;
            parking.ToDateTime = vm.ToDateTime;
            parking.OrderBy = vm.OrderBy;
            
            ParkingAreaDAL parkingDal = new ParkingAreaDAL();
            List<AvailableParkingAreaResult> availableParkingList = parkingDal.GetAvailableParking(parking);
            JavaScriptSerializer js = new JavaScriptSerializer();
            var str = js.Serialize(availableParkingList);
            ViewBag.availableParkingList = str;
            ViewBag.Lat = availableParkingList[0].lattitude;
            ViewBag.Lng = availableParkingList[0].longitude;
            return View(availableParkingList);
        }

        public ActionResult LocateParkingArea() 
          {
              if (Session["userDetail"] != null)
              {
                  return View(); 
              }
              else
              {
                  if (Request["address"] != null)
                      TempData["RequestedUrl"] = "ParkingArea/LocateParkingArea/?lat=" + Request["lat"].ToString() + "&long=" + Request["long"].ToString() + "&address=" + Request["address"].ToString() + "&parkId=" + Request["parkId"].ToString();
                  else
                      TempData["RequestedUrl"] = "ParkingArea/LocateParkingArea/?lat=" + Request["lat"].ToString() + "&long=" + Request["long"].ToString();
                  return RedirectToAction("Login", "TrueWheelsUser");

              }
        }

        [HttpPost]
        public ActionResult AvailableParkingList(string para, string viewModel)
        {
            List<AvailableParkingAreaResult> entity = JsonConvert.DeserializeObject<List<AvailableParkingAreaResult>>(viewModel);
            var result = new List<AvailableParkingAreaResult>();
            if (para == "Distance")
                result = entity.OrderBy(x => x.Distance).ToList();
            else if (para == "Rating")
                result = entity.OrderBy(x => x.Rating).ToList();
            else
                result = entity.OrderBy(x => x.BasicCharge).ToList();
            return PartialView("AvailableParking", result);
        }

        public JsonResult GetParkingdetail(string park_Id)
        {
            ParkingAreaDAL parkingDal = new ParkingAreaDAL();
            var getParkingDetails = parkingDal.GetParkingDetails(park_Id);
            return Json(getParkingDetails, JsonRequestBehavior.AllowGet);
        }

	}
}

TestDev/TrueWheels.Web/Views/ParkingArea/Index.cshtml
@model List<TrueWheels.BEL.AvailableParkingAreaResult>

@{
    ViewBag.Title = "Index";
    <script src="~/Content/js/vendor/jquery-1.10.2.min.js"></script>
     <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        #markers_info .marker {
            height: 40px;
            cursor: pointer;
        }


        .labels {
            color: white;
            background-color: red;
            font-family: "Lucida Grande", "Arial", sans-serif;
            font-size: 10px;
            text-align: center;
            width: 30px;
            white-space: nowrap;
        }
    </style>

    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6v5-2uaq_wusHDktM9ILcqIrlPtnZgEk">
    </script>
    @*<script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=geometry,places&ext=.js"></script>*@
    <script src="https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerwithlabel/src/markerwithlabel.js"></script>
    <script src="~/Js/yourNamespace.yourPageScript.js"></script>
    <script type="text/javascript">
    // put the script section somewhere appropriate in the page
    
    $(document).ready(function () {
        var dropDown = $('#TypeId'); // assuming the ID of this element is 'TypeId'
        dropDown.change(function () {
            yourNamespace.yourPageScript.populateView(dropDown);
        });
    });
</script>
    
     <script type="text/javascript">
        
         function SendOTPMessage() {
             var modelDataJSON = '@Html.Raw(Json.Encode(Model))';

             alert("API will send message at this time(internally)");
             $.ajax({
                 url: '@Url.Action("PopulateType", "ParkingArea")',
                 data: { selectedValue: $(this).val(), vm: Model },
                 cache: false,
                 type: "Get",
                 dataType: "html",
                 success: function (data, textStatus, XMLHttpRequest) {
                      SetData(data);
                 }
             });

             function SetData(data) {
                 $("#partialViewDiv").html(data); // HTML DOM replace
             }
            //$.ajax({
            //    url: "/ParkingArea/PopulateType",
            //    type: 'POST',
            //    data: { selectedValue: "distance", vm: modelDataJSON },
            //    dataType: 'json'
            //    });


         }

         @*$("#TypeID").change(function (event) {
             alert("hvgvg")
             $.ajax({
                url: '@Url.Action("PopulateType", "ParkingArea")',
                 data: { id: $(this).val(), vm: modelDataJSON  /* add other additional parameters */ },
                 cache: false,
                 type: "POST",
                 dataType: "html",
                 success: function (data, textStatus, XMLHttpRequest) {
                   alert("llll")  //SetData(data);
                 }
             });
         });*@
    </script>
    
    <script type="text/javascript">
        var map;
        var markers = [];
        function initialize() {

            var lat = '@ViewBag.Lat';
            var lon = '@ViewBag.Lng';
            var data = '@Html.Raw(HttpUtility.JavaScriptStringEncode(ViewBag.availableParkingList))';
            var availableParkiangList = JSON.parse(data);
            //alert(availableParkiangList[0].lattitude + availableParkiangList[0].longitude + availableParkiangList[0].parking_address);

            map = new google.maps.Map(document.getElementById('map_canvas'), {
                zoom: 15,
                center: new google.maps.LatLng(lat, lon),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });
            //var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);


            var infowindow = new google.maps.InfoWindow();

            var marker, i;

            for (i = 0; i < availableParkiangList.length; i++) {
                var image = 'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2250%22%20height%3D%2250%22%20viewBox%3D%220%200%2038%2038%22%3E%3Cpath%20fill%3D%22%23808080%22%20stroke%3D%22%23ccc%22%20stroke-width%3D%22.5%22%20d%3D%22M34.305%2016.234c0%208.83-15.148%2019.158-15.148%2019.158S3.507%2025.065%203.507%2016.1c0-8.505%206.894-14.304%2015.4-14.304%208.504%200%2015.398%205.933%2015.398%2014.438z%22%2F%3E%3Ctext%20transform%3D%22translate%2819%2018.5%29%22%20fill%3D%22%23dff%22%20style%3D%22font-family%3A%20Arial%2C%20sans-serif%3Bfont-weight%3Abold%3Btext-align%3Acenter%3B%22%20font-size%3D%2212%22%20text-anchor%3D%22middle%22%3E' + (i + 1) + '%3C%2Ftext%3E%3C%2Fsvg%3E';

                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(availableParkiangList[i].lattitude, availableParkiangList[i].longitude),
                    map: map,
                    icon: normalIcon(),
                    title: availableParkiangList[i].parking_address,
                    draggable: false,
                    raiseOnDrag: false,
                    labelContent: "ABCD",
                    labelAnchor: new google.maps.Point(15, 65),
                    labelClass: "labels", // the CSS class for the label
                    labelInBackground: true,
                    icon: image
                    //icon: pinSymbol('green')
                });

                google.maps.event.addListener(marker, 'click', (function (marker, i) {
                    return function () {
                        
                        infowindow.setContent(availableParkiangList[i].parking_address);
                        infowindow.open(map, marker);
                        locatePoint(availableParkiangList[i].lattitude, availableParkiangList[i].longitude , availableParkiangList[i].parking_address,availableParkiangList[i].Parking_id)
                        //alert(availableParkiangList[i].parking_address);
                    }
                })(marker, i));
                markers.push(marker);
            }
        }
        //function pinSymbol(color) {
        //    return {
        //        path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z',
        //        fillColor: color,
        //        fillOpacity: 1,
        //        strokeColor: '#000',
        //        strokeWeight: 2,
        //        scale: 2
        //    };
        //}
        function showMap(lat, lon, address,parkingId) {
            var map = new google.maps.Map(document.getElementById('map_canvas'), {
                zoom: 15,
                center: new google.maps.LatLng(lat, lon),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });
            
            var infowindow = new google.maps.InfoWindow();

            var marker, i;
            marker = new google.maps.Marker({
                position: new google.maps.LatLng(lat, lon),
                map: map
            });
            infowindow.setContent(address);
            infowindow.open(map, marker);
            var url = "/ParkingArea/LocateParkingArea/?lat=" + lat + "&long=" + lon + "&address=" + address + "&parkId=" + parkingId;
            window.location = "http://" + window.location.host + url;
        }
        $('#markers_info .marker').hover(
          // mouse in
          function () {
              alert("in");
              // first we need to know which <div class="marker"></div> we hovered
              var index = $('#markers_info .marker').index(this);
              markers[index].setIcon(highlightedIcon());
          },
          // mouse out
          function () {
              alert("out");
              // first we need to know which <div class="marker"></div> we hovered
              var index = $('#markers_info .marker').index(this);
              markers[index].setIcon(normalIcon());
          }

        );

        function normalIcon() {
            return {
                url: 'http://1.bp.blogspot.com/_GZzKwf6g1o8/S6xwK6CSghI/AAAAAAAAA98/_iA3r4Ehclk/s1600/marker-green.png'
            };
        }
        function highlightedIcon() {
            return {
                url: 'http://steeplemedia.com/images/markers/markerGreen.png'
            };
        }

        function locatePoint(lat, long,address,parkingId) {
            //alert(lat);
            
            var url = "/ParkingArea/LocateParkingArea/?lat=" + lat + "&long=" + long + "&address=" + address + "&parkId=" + parkingId;
            window.location = "http://" + window.location.host + url;
        }
        //google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    @*<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>*@
    <script type="text/javascript">
        $.fn.stars = function () {
            return $(this).each(function () {
                // Get the value
                var val = parseFloat($(this).html());
                // Make sure that the value is in 0 - 5 range, multiply to get width
                var size = Math.max(0, (Math.min(5, val))) * 16;
                // Create stars holder
                var $span = $('<span />').width(size);
                // Replace the numerical value with stars
                $(this).html($span);
            });
        }
        $(function () {
            $('span.stars').stars();
        });

        function load(value)
        {
            var dataViewModel = @Html.Raw(Json.Encode(Model));
            $.ajax({
                url: '@Url.Action("AvailableParkingList", "ParkingArea")',
                dataType: 'html',
                data: { 'para': value ,'viewModel': JSON.stringify(dataViewModel)},
                type: 'POST',
                success: function (result) {
                    $('#idAvailableParking').html(result);
                },
                error: function (xhr) {
                    alert(xhr.statusText);
                }
            });
        }

    </script>
    <style type="text/css">
        span.stars, span.stars span {
            display: block;
            background: url(http://www.ulmanen.fi/stuff/stars.png) 0 -16px repeat-x;
            width: 80px;
            height: 16px;
        }

            span.stars span {
                background-position: 0 0;
            }

        #markers_info .marker {
            height: 50px;
        }
    </style>


}

<h4>Available Parking Area</h4>


<div class="col-lg-12">
   
        @using (Html.BeginForm("Index", "Home", FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
        {
            <div class="input-group input-group-lg">
                @*<input type="text" placeholder="Enter Your Search String" class="form-control" />*@
                @Html.TextBox("destination", "", new { id = "textSearch", @class = "form-control", @placeholder = "Enter Your Search String", @tabindex = "1" })
                <div class="input-group-btn">
                    @*<button type="button" class="btn btn-lg btn-success">Search</button>*@
                    <input type="submit" class="btn btn-lg btn-success" value="Search" onclick="location.href= '@Url.Action("Index", "Home")'">
                    <!--  <input type="button" value="Search" style=" width :15%; height : 80%; border : 1px solid black; border-radius : 4px;" />

                     Button and dropdown menu -->
                </div>
            </div>

        }        
</div>
<div class="col-sm-12"><hr class="colorgraph"></div>

<div id="idAvailableParking">
    @{Html.RenderPartial("AvailableParking", Model);}
</div>

@*<div class="col-lg-3" style="overflow:scroll ;height:80vh">
        <div>
            <input class="label-primary"  value="Sort By" />
            
        </div>
        <div class="list-group  " id="markers_info">
            @{
            var i = 1;
            foreach (var item in Model)
            {

                <a href="#" class="list-group-item marker" onclick='showMap(@item.lattitude,@item.longitude,"@item.parking_address")'>
                    <span class="badge" style="color: #dff">@i</span>

                    @item.parking_address<br />
                    @item.BasicCharge<br/>
                    @item.Rating<br/>
                    @item.Distance<br/>
                    <span class="stars">@item.Rating</span>
                </a>

                i = i + 1;
                
            }
            }
        </div>

    </div>*@

<div class="col-lg-9">
    <div>
        <div id="map_canvas" style="height:80vh"></div>
    </div>
</div>

@*<div class="form-group">
   
    <div class="col-md-10">
        @Html.DropDownList("TypeID", new List<SelectListItem> { 
                       new SelectListItem { Value = "No_Of_Space_Avaiable" , Text = "No_Of_Space_Avaiable" },
                       new SelectListItem { Value = "Distance" , Text = "Distance" },
                       new SelectListItem { Value = "Parking_id" , Text = "Parking_id" }
                    }, "value",
                 new {@onchange = "SendOTPMessage();" }
                  )
        
    </div>
</div>*@
@*<div id="partialViewDiv">
    @Html.Partial("_ListParking", Model);
</div>*@

@*@{
   
        
    @Html.Partial("_ListParking",Model.OrderBy(e => e.SpaceType))
}*@

<script type="text/javascript">initialize();</script>


TestDev/TrueWheels.Web/Views/ParkingArea/LocateParkingArea.cshtml
@model IEnumerable<TrueWheels.Web.Models.LocateParkingViewModel>

@{
    ViewBag.Title = "LocateParkingArea";
    <style>
        html,
        body,
        #map_canvas {
            height: 300px;
            width: 100%;
            margin: 5px;
            padding: 0px;
            
        }
    </style>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6v5-2uaq_wusHDktM9ILcqIrlPtnZgEk&libraries=places"></script>
  
    <script type="text/javascript">

        var map;
        var servicec;

        function GetParameterValues(param) {
            var url = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
            for (var i = 0; i < url.length; i++) {
                var urlparam = url[i].split('=');
                if (urlparam[0] == param) {
                    return urlparam[1].replace(/\%20/g, ' ');
                }
            }
        }

        function getParameterByName(name, url) {
            if (!url) url = window.location.href;
            name = name.replace(/[\[\]]/g, "\\$&");
            var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            return decodeURIComponent(results[2].replace(/\+/g, " "));
        }
        function initMap(crd) {
            //alert("hi");
            //alert(crd.latitude);
            var currentLatt;
            var currentLong;
            var latt = getParameterByName('lat') * 1.0;
            var long = getParameterByName('long') * 1.0;
            //alert(currentLatt);
            //alert(Number(currentLatt);
           
            var source = new google.maps.LatLng(crd.latitude, crd.longitude);
            var destination = new google.maps.LatLng(latt, long);

            var parkingName = GetParameterValues('address');

            function GetParameterValues(param) {
                var url = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
                for (var i = 0; i < url.length; i++) {
                    var urlparam = url[i].split('=');
                    if (urlparam[0] == param) {
                        return urlparam[1].replace(/\%20/g, ' ');
                    }
                }
            }
            
            map = new google.maps.Map(document.getElementById('map_canvas'), {
                center: source,
                scrollwheel: true,
                zoom: 7
            });


            var directionsDisplay = new google.maps.DirectionsRenderer({
                map: map
            });

            // Set destination, origin and travel mode.
            var request = {
                destination: destination,
                origin: source,
                travelMode: google.maps.TravelMode.DRIVING//
            };

            // Pass the directions request to the directions service.
            var directionsService = new google.maps.DirectionsService();
            directionsService.route(request, function (response, status) {
                if (status == google.maps.DirectionsStatus.OK) {
                    // Display the route on the map.
                    directionsDisplay.setDirections(response);
                }
            });
           
            //var request = {
            //    location: destination,
            //    radius: '500',
            //    query: 'restaurant'
            //};

            //service = new google.maps.places.PlacesService(map);
            //service.textSearch(request, callback);
            service = new google.maps.places.PlacesService(map);

            // The idle event is a debounced event, so we can query & listen without
            // throwing too many requests at the server.
            map.addListener('idle', performSearch);

            $('div#ParkingName').html(parkingName);

            directionsDisplay.setMap(map);
            directionsDisplay.setPanel(document.getElementById('right-panel'));

            calculateAndDisplayRoute(directionsService, directionsDisplay);

            function calculateAndDisplayRoute(directionsService, directionsDisplay) {
                var start = source;
                var end = destination;
                directionsService.route({
                    origin: start,
                    destination: end,
                    travelMode: 'DRIVING'
                }, function (response, status) {
                    if (status === 'OK') {
                        directionsDisplay.setDirections(response);
                    } else {
                        window.alert('Directions request failed due to ' + status);
                    }
                });


            }
            function performSearch() {
                service = new google.maps.places.PlacesService(map);
                var request = {
                    bounds: map.getBounds(),
                    types: ['shopping_mall', 'restaurents'],
                    //keyword:'famous',
                    radius: 100,
                    openNow: true,

                };
                service.nearbySearch(request, callback);
            }

            function callback(results, status) {
                if (status !== google.maps.places.PlacesServiceStatus.OK) {
                    console.error(status);
                    return;
                }
                var mydiv = document.getElementById("markers_info");
                for (var i = 0, result; result = results[i]; i++) {
                    //addMarker(result);
                    var place = result;
                    service.getDetails(place, function (result1, status) {
                        if (status !== google.maps.places.PlacesServiceStatus.OK) {
                            console.error(status);
                            alert(status);
                            return;
                        }
                        //infoWindow.setContent(result.name);
                        //alert(result1.name);

                        var aTag = document.createElement('a');
                        aTag.setAttribute('href', "#");
                        aTag.setAttribute('class', "list-group-item marker");
                        aTag.innerHTML = result1.name;
                        mydiv.appendChild(aTag);
                    });
                }
            }
        }
        
        $(document).ready(function () {
            var parkingName = GetParameterValues('parkId');

            $.ajax({
                url: '@Url.Action("GetParkingdetail", "ParkingArea")',
                data: { park_Id: parkingName },
                cache: false,
                type: "Get",
                dataType: "JSON",
                success: function (data) {
                    $('#idDescription').html(data.Description);
                    //$('#ReviewComments').html(data.Description);
                },
                //error: function (xhr) {
                //    debugger
                //    alert(xhr.statusText);
                //}
            });
        });
    </script>

}
<div id="ParkingName"><h4></h4>
</div>
@*@{
<h4>@Html.DisplayNameFor(model => model.AddressName)</h4>
}*@
@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartLat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartLong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndLat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndtLat)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartLat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartLong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndLat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndtLat)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

    </table>*@

    <div class="col-lg-8">
        <div class="row">
            <div id="map_canvas" style="width: 100%; height: 500px"></div>
        </div>
        <div class="col-lg-12">

            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Description</h3>
                </div>
                <div id="idDescription" class="panel-body">
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Review & Comments</h3>
                </div>
                <div class="panel-body">
                    Panel content
                    <p>...</p>

                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Facilities</h3>
                </div>
                <div class="panel-body">
                    Panel content
                    <p>...</p>

                </div>
            </div>
        </div>
    </div>


    <div class="col-lg-4">
        
            @*<div class="form-group">
                    <form>
                        <input type="text" class="form-control" placeholder="From" />
                        <input type="text" class="form-control" placeholder="To" />
                    </form>
                </div>*@
                <div id="right-panel" style="height:200px;overflow-x:hidden;overflow-y:scroll"></div>
           
        
                <h4>Near by parking area</h4>
                <hr />
                <div class="list-group" id="markers_info" style="height:200px;overflow-x:hidden;overflow-y:scroll">

                </div>
            
    </div>

<script type="text/javascript">

    var options = {
        enableHighAccuracy: true,
        timeout: 7000,
        maximumAge: 0
    };
    var crd;
    function success(pos) {
        crd = pos.coords;
        console.log('Your current position is:');
        console.log('Latitude : ' + crd.latitude);
        console.log('Longitude: ' + crd.longitude);
        console.log('More or less ' + crd.accuracy + ' meters.');
        initMap(crd);
    };

    function error(err) {
        console.warn('ERROR(' + err.code + '): ' + err.message);
    };
    navigator.geolocation.getCurrentPosition(success, error, options);
</script>